zookeeper:
  enabled: true
  replicaCount: 1
  image:
    repository: wurstmeister/zookeeper
    tag: "latest"
  env:
    - name: ZOOKEEPER_CLIENT_PORT
      value: "2181"
    - name: ZOOKEEPER_TICK_TIME
      value: "2000"
  service:
    type: ClusterIP
    ports:
      clientPort: 2181

kafka:
  enabled: true
  replicaCount: 1
  image:
    repository: wurstmeister/kafka
    tag: "latest"
  config:
    KAFKA_BROKER_ID: 1
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
    KAFKA_LISTENERS: INSIDE://0.0.0.0:9092
    KAFKA_LISTENER_NAMES: INSIDE
    KAFKA_LISTENER_SSL_CERTIFICATE: false
  service:
    type: ClusterIP
    ports:
      kafkaPort: 9092